### PR TITLE
Add new APIs for variadic cluster commands

### PR DESCRIPTION
**Pull request by bjosv**
- valkeyClustervCommandToNode()
- valkeyClustervAppendCommandToNode()

From https://github.com/Nordix/hiredis-cluster/pull/231

### CODE REVIEW

**Review by zuiderkwast — APPROVED** [review]
Yes, these are just missing variants.

The spellcheck error is not introduced here. Should be fixed in another PR. (Just add "valkey" to the wordlist?)

**Comment by bjosv** [comment]
Yes, its seems to complain about following text in standalone.md.
`See [include/valkey.h](include/valkey.h) for more details`
Weird though..possible a simple fix, or alternatively we replace spellcheck with `typos` as in the valkey repo

**Comment by bjosv** [comment]
Adding the word seem to be enough this time

**Comment by zuiderkwast** [comment]
It may be the case that the spellchecker ignores text within backticks. I have a vague memory of this. If so, we could silence this kind of errors by placing backticks around the file name.

**Pull request merged**
