### PR TITLE
Cleanup of unused and superfluous code in `src/vkutil.*`

### PR DESCRIPTION
**Pull request by bjosv**
- Remove unused code in `src/vkutil.*`
- Remove macro `NOT_REACHED()`.
- Remove function `vk_valid_port()`.
- Remove own assert macro in cluster code.
  We have a mixed usage of own and standard assert. Lets use standard from <assert.h> only.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Failing jobs?

**Comment by bjosv** [comment]
> Failing jobs?

Yes, seem to be some issue with windows that needs to be corrected. CentOS fails due to some install server

**Comment by bjosv** [comment]
Yes, we should replace CentoOS 7 and run clang-tidy on everything, I has never passed in libvalkey after the merge.
Lets add issue on those two things

**Comment by bjosv** [comment]
Added #42 and #43

**Pull request merged**
